export const SN_PREFIX = 'sn'
export const LOGIN_COMP_NAME = 'snail-login'
export const LAYOUT_COMP_NAME = 'snail-layout'
export const ESLINT_PLUGIN_NAME = 'snail-eslint-config'
export const VITE_PLUGIN_NAME = 'snail-vite-plugins'
export const USE_PLUGIN_NAME = 'snail-use'
export const UTILS_PLUGIN_NAME = 'snail-utils'
export const CLI_PLUGIN_NAME = 'snail-cli'
